### ISSUE TITLE
Check relationship whether exists or not before copying

### ISSUE THREAD

**Issue by Deepanshu2017** [skypointcloud/skypoint-python-cdm-connector#1]
https://github.com/skypointcloud/skypoint-python-cdm-connector/blob/9fd4101aec247dd7a009def39fcb835022a7765f/skypoint_python_cdm/Model.py#L350

In code look starting at the above mentioned line, check if the relationship exists or not before copying it into new model.json object.

@Deepanshu2017 @GautamKumarSkyPointCloud

**Comment by TissonMathew** [comment]
@mashray review and close if this fixed.
