### ISSUE TITLE
Incorrect blob_url

### ISSUE THREAD

**Issue by biztalk** [skypointcloud/skypoint-python-cdm-connector#2]
I have started testing this and I noticed that the  blob_url is missing the "directory name".

currently the url is like this: 
`"https://<storage>.dfs.core.windows.net/<container>/customEntity/customEntity.csv.snapshots-dd-mm-yyyy-hh-MM-ss/customEntity0.csv"`

In fact the correct url should be like this: 
`"https://<storage>.dfs.core.windows.net/<container>/<dataflow_name>/customEntity/customEntity.csv.snapshots-dd-mm-yyyy-hh-MM-ss/customEntity0.csv"`

**Comment by TissonMathew** [comment]
@mashray can you review and fix? thanks @biztalk

**Comment by mashray** [comment]
@biztalk Hey thank you for the testing. The changes have been made.

**Comment by TissonMathew** [comment]
This issue is fixed. Closing.
